// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKCL3ndNQ53-wvzEOI8W7w_g3iBkFMG4k',
    appId: '1:889058578554:web:0e4f699ac6e24c288a6bc3',
    messagingSenderId: '889058578554',
    projectId: 'miyuki-ab282',
    authDomain: 'miyuki-ab282.firebaseapp.com',
    storageBucket: 'miyuki-ab282.appspot.com',
    measurementId: 'G-PVRSWX6CXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjOyEr_bpNI50BmLC3K4ikkt7qlVghscE',
    appId: '1:889058578554:android:33f88bca8928f3558a6bc3',
    messagingSenderId: '889058578554',
    projectId: 'miyuki-ab282',
    storageBucket: 'miyuki-ab282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWN2qqJZ9wOZVjYdBc9lVk1479-xiRU8',
    appId: '1:889058578554:ios:0ff330284f2c9ddf8a6bc3',
    messagingSenderId: '889058578554',
    projectId: 'miyuki-ab282',
    storageBucket: 'miyuki-ab282.appspot.com',
    iosBundleId: 'com.example.miyuki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWN2qqJZ9wOZVjYdBc9lVk1479-xiRU8',
    appId: '1:889058578554:ios:104e1aec1ccd54ea8a6bc3',
    messagingSenderId: '889058578554',
    projectId: 'miyuki-ab282',
    storageBucket: 'miyuki-ab282.appspot.com',
    iosBundleId: 'com.example.miyuki.RunnerTests',
  );
}
